version: "3.9"

services:
  jenkins:
    # image: jenkins/jenkins:alpine-jdk11
    build: ./jenkins-build
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
      JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin

 
  nginx_tst1:
    build: ./nginx_agent
    ports:
        - 8083:80
    expose:
      - 22:22
    tty: true  
  
